name: API Tests - Full Suite (Node.js 22 LTS)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug - List key folders
      run: |
        echo "=== File Structure ==="
        find . -type f -maxdepth 3
        echo "=== collections/ ==="
        ls -R collections/ || echo "Missing collections/"
        echo "=== configs/ ==="
        ls -R configs/ || echo "Missing configs/"
        echo "=== data_sets/ ==="
        ls -R data_sets/ || echo "Missing data_sets/"
        echo "=== reports/ ==="
        ls -R reports/ || echo "Missing reports/"

    - name: Setup Node.js (latest LTS)
      uses: actions/setup-node@v4
      with:
        node-version: '22' 

    - name: Install dependencies globally
      run: npm install -g newman newman-reporter-htmlextra

    - name: Ensure reports directory exists
      run: mkdir -p reports

    - name: Test Newman Installation
      run: |
        newman --version
        echo "Newman is ready"

    - name: Run User Management Tests
      run: |
        newman run collections/01_User_Management.postman_collection.json \
          -e configs/qa_env.postman_environment.json \
          -r htmlextra \
          --reporter-htmlextra-export reports/User_Management_Test_Report.html \
          --reporter-htmlextra-browserTitle "User Management Test Report" \
          --reporter-htmlextra-title "User Management API Test Summary"
      continue-on-error: true

    - name: Run Authentication Tests
      run: |
        newman run collections/02_Authentication.postman_collection.json \
          -e configs/qa_env.postman_environment.json \
          -r htmlextra \
          --reporter-htmlextra-export reports/Authentication_Test_Report.html \
          --reporter-htmlextra-browserTitle "Authentication Test Report" \
          --reporter-htmlextra-title "Authentication API Test Summary"
      continue-on-error: true

    - name: Run Data-Driven Tests
      run: |
        newman run collections/03_Data_Driven.postman_collection.json \
          -e configs/qa_env.postman_environment.json \
          -d data_sets/product_data.json \
          -r htmlextra \
          --reporter-htmlextra-export reports/Data_Driven_Test_Report.html \
          --reporter-htmlextra-browserTitle "Data Driven Test Report" \
          --reporter-htmlextra-title "Data Driven API Test Summary"
      continue-on-error: true

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: API-Test-Reports
        path: reports/
        if-no-files-found: warn
